### ISSUE TITLE
img2img inpaint 

### ISSUE THREAD

**Issue by PotatoBananaApple** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#110]
Something seems to be causing img2img inpaint to apply upscaler?... on whole image and not only on the masked area. Is this intended?

After generating few times through inpaint it becomes very obvious. 
1 pic: Masked area i used
2 pic: The starting point
3 pic: After generating and cycling through inpaint 3-4 times, with similar masked area to the first picture.

![up](https://user-images.githubusercontent.com/130109414/230510880-ee2fb31c-8cf8-4740-9322-f5f88b819e1b.jpg)

settings i had when generating the image

![sett](https://user-images.githubusercontent.com/130109414/230511081-9a048e5a-8020-4109-b6ae-8403b9152b50.jpg)

python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.17.dev464  •  gradio: 3.23.0

**Comment by PotatoBananaApple** [comment]
When the Upscaler is set to none, only the masked area changes.

**Comment by pkuliyi2015** [comment]
Yes, this is intended. 

Many users found that the SD img2img is not ideal in some areas, but they still want to process these areas with some non-upscaling ESRGAN variants. Otherwise, it is too blurry.

Therefore, I still apply upscaler to those unmask areas. For those who don’t want to use upscaler you just select None.

In this way, the extension reaches its max compatibility to everyone’s need.

**Comment by PotatoBananaApple** [comment]
Makes sense.

And thanks for the extension, the difference it makes is like comparing night and day! 😎

**Comment by pkuliyi2015** [comment]
You are welcome and also, thanks for your feedback!
