### ISSUE TITLE
Is there something I'm missing? 

### ISSUE THREAD

**Issue by Marcusgeorgiadis** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#15]
I cannot get good results with this in i2i upscaling. Outputs are decent, but seemingly not better than ultimate SD upscale. Can you give some example settings for upscaling? And give annotations to settings explaining what they do?

Also have no idea how to properly apply this in t2i.

**Comment by LightChaser666** [comment]
Thanks for your feedback. Please refer to another issue, where we have tons of discussion on how to use it well. 

Personally speaking MultiDiffusion for upscale is more difficult to use than Ultimate Upscaler because the latter preserves details with post-processing. MultiDiffusion is a completely redraw, so it **largely depends on your checkpoint** and your settings for img2img. With a good checkpoint (better not pruned) it can achieve amazing and desirable results.

So if you are not very experienced in img2img you may need to try it more.

**Comment by Marcusgeorgiadis** [comment]
I have referenced the examples in the other threads, they only use anime as examples. For anime it's not hard to upscale.

I'm experienced in i2i, I just don't see how this is any better than ultimate SD upscale.

Just need more comprehensive instructions. Some settings are intuitive, some I have no clue what they do.

**Comment by jurandfantom** [comment]
Here is example @Marcusgeorgiadis 
Problem with that extension (and upscale in general) is fact that everything change a lot. Today i was checking all samplers to find best one and end up with ranking that depends from situation. Attached picture shows exactly what I talk about, left is MultiDiffusion when right is Ultimate.
![23,03,11 - 21,49,01 - 7348 a](https://user-images.githubusercontent.com/30580568/224512909-d400c411-ba0f-4238-a353-86953ac13774.png)

Here is best attempt with Ultimate as comparison point for above picture. What is better/worse? hard to say, only thing that matter is output please you or not. Apply everything as we do in other topic and consider that as best starting point. Everything change results a lot, SD model, upscaler, sampler, type of extension + CFG/Denoiser. Try find mix that please you as that or other extension is not silver bullet (that one is way faster )
![23,03,11 - 18,25,32 - 7341 a](https://user-images.githubusercontent.com/30580568/224512833-4a92b24a-ee5e-43da-8a14-8543de46dfef.jpg)

**Comment by pkuliyi2015** [comment]
> Here is example @Marcusgeorgiadis Problem with that extension (and upscale in general) is fact that everything change a lot. Today i was checking all samplers to find best one and end up with ranking that depends from situation. Attached picture shows exactly what I talk about, left is MultiDiffusion when right is Ultimate.

The key point is that I need a user interface to draw bbox, so that you can draw rectangles and control the MultiDiffusion with different prompts. In this way the result should get way better.

Why? because in this way you can just select the woman's face and tell SD to draw a beautiful woman's face. Then the SD will try his best, using his 512 * 512 resolution to ONLY draw a face. The resolution will be unprecedentedly high for SD models, as he dedicated to draw only one part of the image at the best of his capabilities.

However, when I was adding features I saw this f**king issue:
https://github.com/gradio-app/gradio/issues/2316

Some one pr a bbox tool but the officials denied the merging:
https://github.com/gradio-app/gradio/pull/3220

I don't know what are they thinking in mind to deny such a good PR (from my perspective) but don't provide their own solutions. It has been a half year since it first proposed.

So it will be hard to draw rectangles on images directly. I must find another way to draw rectangles. Do you have any other idea?

**Comment by pkuliyi2015** [comment]
Please try again in this version. The problem should be fixed now.
