### ISSUE TITLE
Tiled Noise Inversion for better upscaling 方法原理

### ISSUE THREAD

**Issue by yue-gang** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#162]
您好，方便介绍一下Tiled Noise Inversion for better upscaling方法的原理吗？

**Comment by Kahsolt** [comment]
Noise Inversion allows us to find the approximated **initial noise** for any arbitrary image given, corresponding to the current model weights. This certain noise contains a prior info about the image, rather than a new random noise used as in normal img2img way, hence promised not to change painting structure too much during sampling process.

To understand exactly how, read webui's implementation at `scripts\img2imgalt.py`
