### ISSUE TITLE
Karras samplers perform poorly

### ISSUE THREAD

**Issue by Rkkss** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#163]
While ancestral, non-ancestral change the color. Karras samplers seems to do exact opposite, it wash out color, the amount of details added also below the bar compare to other samplers. 
 I ran few test on different upscalers & VAEs. This behavior is very consistent across all the samplers. Is this normal?

https://imgsli.com/MTc0OTk1/3/4

**Comment by SLAPaper** [comment]
For your image providing, I think the non-karras version is a bit too oversaturated...

**Comment by Rkkss** [comment]
> For your image providing, I think the non-karras version is a bit too oversaturated...

Sry that i wasn't clear. 
You can split samplers into 3 categories: non karass-non ancestral;  ancestral; karass. The first one (heun, DDIM, euler, SDE) perform as expected. Ancestral samplers oversaturate picture but depend on VAE being used. Karass samplers however always wash out pictures compare to other samplers.
This behavior doesn't happen in Ultimate SD upscaler.

**Comment by PotatoBananaApple** [comment]
Check ControlNet v1.1.126 tile resample. Works with multidiffusion. Insane combo, seems to do well with karras.
![image](https://user-images.githubusercontent.com/130109414/235835525-a97eb525-ddfb-475f-8f6b-84b6a2839818.png)

**Comment by Kahsolt** [comment]
Ancestral and Karras are both noise scheduling technics. 
From the examples provided, Ancestral gives more saturated results while Karras is right the opposite, for the moment I cannot tell if it is a bug or feature.

However, if it does not happen in `Ultimate SD upscaler` and **you are using img2img pipeline**, I would possibly guess the color-shift is caused by GroupNorm stats estimation error. What about having a try to disable `Fast Encoder`?

PS: It is also known that `Fast Decoder` might also introduce a bit of color-shift, but decoding without gn_approx is unbearable slow (than encoding).

**Comment by Rkkss** [comment]
> Check ControlNet v1.1.126 tile resample. Works with multidiffusion. Insane combo, seems to do well with karras. ![image](https://user-images.githubusercontent.com/130109414/235835525-a97eb525-ddfb-475f-8f6b-84b6a2839818.png)
![Untitled](https://user-images.githubusercontent.com/127614350/235984089-6e472386-fda3-4808-b4e4-d228b25991e3.jpg)

Haven't tested new tile model alot but getting this error often when I tried it with multidiffusion
