### ISSUE TITLE
Can it be ported to comfyui ?  能否为comfyui适配插件？

### ISSUE THREAD

**Issue by yaosd99** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#291]
This plugin is essential for me to use webui, and I hope the author can port it to comfyui. 
thanks.

**Comment by Kahsolt** [comment]
Possibly NOT.
Once upon a time there's a friend tried, but at last gave up, left the dangling repo [comfy_tiled_diffusion)](https://github.com/Kahsolt/comfy_tiled_diffusion), no further development.

**Because the implementation is strongly depended on the sd-webui framework, migrating to anywhere else requires a total re-implementation.**

Find somebody paid to do this.

**Comment by Kahsolt** [comment]
try use this [https://github.com/BlenderNeko/ComfyUI_TiledKSampler](https://github.com/BlenderNeko/ComfyUI_TiledKSampler)
