### ISSUE TITLE
Strange message in terminal after updating this extension today [commit aa47321]

### ISSUE THREAD

**Issue by genialgenteel** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#319]
Hello,

After opening and restarting SD and doing an auto update for my extensions, I got a weird message:

```
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Receiving objects: 100% (3/3), 338 bytes | 338.00 KiB/s, done.
Resolving deltas: 100% (2/2), completed with 2 local objects.
From https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111
 + e93a013...aa47321 main       -> origin/main  (forced update)
Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'NAME@COMPUTERNAME.(none)')
Couldn't perform 'git pull' on repository in 'C:\Users\NAME\Pictures\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111':

```

What in the world is this and why is it trying (and fortunately failing) to find my email address?
I didn't commit anything to this repository, and I'm not a programmer so I'm not really sure what's going on here. I'm just an end user. Can anyone help, or did anyone see anything similar today? (10/19/2023)

Thanks!

**Comment by Kahsolt** [comment]
Don't panic bro~ you are not required to provide these info.

Try remove and reinstall this extension, configurations should be correct.
If not, ref also: 
- [https://github.com/microsoft/vscode/issues/114168](https://github.com/microsoft/vscode/issues/114168)
- [https://github.com/microsoft/vscode/issues/112294](https://github.com/microsoft/vscode/issues/112294)
- [https://github.com/edward-shen/MMM-pages/issues/7](https://github.com/edward-shen/MMM-pages/issues/7)

Q: What in the world is this?
A: For the git developers, they are suggested to configure their **display name** and **email**, so that each commit they contribute binds to a recognizable somebody. It is just used for code developers to distinguish how did what and find whom to blame when a commit causes failure.
**Git knows nothing until user tells it**, and it is even no matter you a fake name and email. these info can be even **not related to github account**,
