### ISSUE TITLE
[Need Help] Incorrect Tile Generation on New Apple M3 Max

### ISSUE THREAD

**Issue by gongzhang** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#331]
Hello!

I've encountered an issue with the simplest **Tiled Diffusion** on my Mac with the Apple M3 Max chip. **Each tile seems to generate a different small image, and these images are stacked together without achieving a seamless stitching effect** (see attached image). The exactly same a1111 repo and `venv`, when copied to another computer with an old M1 Max, does not exhibit this problem.

Original image (512x512):
<img src="https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/4470629/fd81f73e-75ec-43b9-9899-9a0bf3fd6e4c" width="300px"/>

Bad Tiled Generation (1204x1024):
<img src="https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/4470629/c8eec773-4510-41d7-8756-abef9a3e3823" width="300px"/>

Could you provide any clues to resolve this issue? Additionally, **I encounter the same problem when using the LDSR Upscaler built into the a1111 repository**.

(I have tried various versions of dependencies, including the latest releases)
version: v1.6.0 • python: 3.10.13 • torch: 2.1.1

**Comment by Svring** [comment]
A common problem of any tile-based method is multiple bodies under high denoising strength, the solution could be either lower down the denoising strength, which leads to higher resolution but no more details than before, or combined with Controlnet-Tile, a model used to maintain the structure of picture so that it could be redrawn to a higher resolution without drastic changes(such as multiple person)
So try to activate controlnet-tile before generating, and set denoising strength at a comparatively low level, may be 0.6, then the problem should be resolved.

**Comment by gongzhang** [comment]
@Svring Thanks for the detailed reply :) I'll try `controlnet-tile`. But the weird thing is the issue was occurred during txt2img, where I can't set the denoising strength.
