### ISSUE TITLE
Can we get some actual directions on how to use this?

### ISSUE THREAD

**Issue by gruevy** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#35]
There's not enough info in the readme to actually use this extension if you don't already know exactly how it's supposed to work. Should I be on the txt2img tab or img2img tab? Do I use both multidiffusion and tiled vae at the same time? I've got it to do 'something' but all my results are failures, so I'm missing something important somewhere.

Basically can we get some real directions on how to use this?

**Comment by pkuliyi2015** [comment]
I'm sorry that I may not be very clear, but the MultiDiffusion is not that easy to use, and its production-usage are quite limited (three options):

1. Image redraw and upscale (img2img)
2. Wide image drawing (txt2img)
3. large image generation with ControlNet (txt2img).

I put example images in each part, you can refer to them for guidance. And if you don't have the three option need you don't need MultiDiffusion, until I updated the function of regional prompt control (so that you can control every region you draw and generate much larger images than usual. It is about to complete.).

However, currently you can always keep the Tiled VAE enabled, as it effectively saves your VRAM at nearly no cost. It is a pure optimization compatible with almost all extensions. For example, if  you like to use highres.fix, you now can upscale the image larger with Tiled VAE enabled

**Comment by gruevy** [comment]
I got the upscale to work, and it was fast and the results were impressive. Took about a minute to go from 768x768 to 3072x3072. I suggest adding directions like this:

To upscale:
1 - Send your image to the img2img tab. Adjust the width and height to match the image. Turn down the denoising strength to 0.2. The prompt can be left blank. 
2 - Enable Multidiffusion. Select an upscaler in the Multidiffusion area. Select your desired scale factor (for example, x4)
3 - Enable Tiled VAE. Leave its settings as default.
4 - Hit Generate.

**Comment by gruevy** [comment]
I think I got the panorama to work, but it looks tiled instead of smooth. That might be because my prompt was too complicated. Here are the steps I used, in case you want to add something like this to the readme as well:

To generate a wide panorama image:
1 - On the txt2img tab, input the prompt. Simple prompts work better. Select the sampler and sampling steps.
2 - Enable Multidiffusion. Check the box for Overwrite Image Size and choose a new image size, IE, a very wide one.
3 - Hit Generate.

Note: Enabling Tiled VAE is optional. Results will be slower, but may have fewer seams.

**Comment by s-ilent** [comment]
I'm also having trouble understanding how to get good results from the instructions. On small images (384x640) that complete fast using normal img2img, Multidiffusion takes about 10-20 minutes. Upscaling an image 2x to 1536x2560 took 5 hours on a 3090Ti, using the default settings. Am I just misunderstanding what the intended use case is here?

**Comment by pkuliyi2015** [comment]
The performance issue definitely comes from wrong parameter settings. Check here for my params. https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/3#issuecomment-1474541273

**Comment by s-ilent** [comment]
Using those recommendations, I still get poor performance on large images. I've copied your parameters [from here](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/3#issuecomment-1474551332), so the parameters should be correct. 

Performance is only slightly slower than normal img2img on a 384x640 image, but with much lower quality than normal img2img. 

On a 768x1280 image, there was no result after 30 minutes, so I terminated it. Please provide more details on the settings you use.

**Comment by neggles** [comment]
1. Set width and height to your source/input image's dimensions.
2. Set scheduler to DPM++ 2M/SDE Karras or DDIM, probably use whichever you generated with originally
3. Set steps to somewhere around 15-30 probably?
4. Set batch count and size to 1.
5. Set denoising strength to something somewhere between 0.2 and 0.3, probably. 
6. Set CFG scale to... something. somewhat higher than what you used to generate in the first place may work quite well, depends on model.
7. Under MultiDiffusion:
   - Check "Enable MultiDiffusion" and "Keep input image size" boxes
   - For a 3090Ti, set latent tile width and height to 96, overlap to 32 or 48, batch size to 1 for now (you can likely increase this all the way to 8 later, but with fp32 models i had some memory exhaustion issues
   - Select an upscaler and a scale factor.
8. Under Tiled VAE:
   - Check "Enable" box, optionally check "Move VAE to GPU" - I've been checking that box but not entirely sure if it's beneficial or not yet
   - Set Encoder tile size to 1280 initially; this is way lower than should be necessary, but will ensure it works & you don't run into "I am out of RAM" slow mode
   - Check "Fast Encoder", "Fast Decoder", and "Encoder Color Fix" options

With these settings I'm able to do a 2x upscale on a 960x1152 source image in ~70 seconds on a 4090.

**Comment by s-ilent** [comment]
Thanks! These instructions work. Comparing to the previous settings, I guess my issues were coming from using a high batch size and the recommended larger tile size with the default large VAE tile size.

**Comment by Zullian** [comment]
I apologize in advance for long and maybe confusing comment, but I started learning stable diffusion a week ago, and I've been at it for like 16 hours a day, no rest for the wicked!

Would it be possible to give detailed explanation of the process, maybe even with pictures, cus for the last 8 hours I've been experimenting with all sort of diffrent values, to find the best output, and with no previous knowledge on this topic, It's very confusing and exhausting.

So far my conclusion is:
Latent tile width & Latent tile height are better in smaller size (64)
Encoder Tile Size is best when used at 512 (64x8=512)

I even tried Encoder Tile Size=256 and I got even more detail in picture, but I lost some color, which Encoder Color Fix did fix indeed, but then I lost the detail. (from what I read in some comment 256 tile should be avoided cus models work best on 512x512), maybe it should be used only for background where I got more detail but not on person, especially on skin.

Example:
I don't know if nudes are allowed here, so I professionally dressed them (ignore tile seams, I did very low value cus I'm trying to understand what's happening)

Latent tile width/height 64, Encoder tile size 256 - more detail 
![Latent tile width_height 64, Encoder tile size 256](https://user-images.githubusercontent.com/3374100/234393329-e2c65fbc-e3b1-41d2-8b50-9f342235f35e.png)

Latent tile width/height 64, Encoder tile size 256, color fix - less detail
![Latent tile width_height 64, Encoder tile size 256, color fix](https://user-images.githubusercontent.com/3374100/234393341-96ea34c1-622d-44c1-a087-fdc72f21928e.png)

Tested in img2img upscale from 512 > 1024 (for faster results, so I'm not sure if those factors apply when upscaling from 1024 to higher)

Also is it better to upscale only by value of 2, or we can do more, cus I saw that with same prompts my original picture was created I get more details when upscaling by x2 and no glitches (denoise of ~0.2 or so), than when upscaling by x4 (then I have more glitches, let's say faces and body parts started appearing everywhere, this could be due to wrong parameters ofc, which I have hard time understanding)
![image](https://user-images.githubusercontent.com/3374100/234398201-b3ae6542-3f7c-4836-ba15-e41da466dce5.png)
![image](https://user-images.githubusercontent.com/3374100/234398514-eda1bd32-ae71-49f8-a097-77fbf449add8.png)

So I understood what Latent tile width & Latent tile height are,
But I have no idea what Encoder Tile Size is and Decoder Tile Size

P.S. (I think Encoder Tile Size is the resolution original picture will be split by)

So more tiles from original picture to process, should give better details and I guess more glitches.

What are your recommendations like:
- Upscale only by x2?
- When upscaling from 512>1024 what are optimal parameters?
- When upscaling from 1024>2048 parameters?
- When upscaling from 1024>4096 paremeters (or it should be avoided to get more details by x2 upscales)?

Also I didn't find any info regarding Noise inversion, some explanaion/samples would be nice.
![image](https://user-images.githubusercontent.com/3374100/234394850-107c95cf-fbc9-422d-8740-e04a59f458d6.png)

I have 3090TI and default paremeters for Tiled VAE were 3072 and 192, so when I tried to upscale 2048 by x2 I get CUDA error, cus Tiled VAE wasn't even applied, which CMD did say, but for ppl with no knowledge it is kinda confusing tho.

Also I would suggest "4x_NMKD-Siax_200k" upscaler which I found a lot better than "4x-UltraSharp" for adding details (I'd say like 2-4 times better) from https://upscale.wiki/wiki/Model_Database (haven't tried Remacri tho)

I love your extension and as someone somewhere wrote it made huge leap in upscalers, I compared it to Extras tab upscale, SD upscale and Ultimate SD upscale (which I haven't had time to test thoughtfully), and your is fastest and supports low end GPU-s.

Kudos for making it compatible with inpaint and masks, would be nice if it would be possible to draw masks and define upscale parameters in one go, but I read somewhere it's not possible.

BTW I encountered bug with "X/Y/Z plot" script when trying to compare different results like denoise, I wanted to see more results to compare and use the best one, for the 1st one on the list it did as it should, for the 2nd one it started upscaling it by double the original value, for the 3rd I guess double again (was taking long time so I canceled it).

**Comment by pkuliyi2015** [comment]
Thank you for paying attention to this extension. Here is a relatively complete civitai tutorial: https://civitai.com/models/34726/tutorial-for-multidiffusion-upscaler-for-automatic1111-detail-to-the-max
