### ISSUE TITLE
Encoder and Decoder Tile Size

### ISSUE THREAD

**Issue by AIAMIAUTHOR** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#7]
The upscaler is amazing, the performance is great, and it was a necessary step in the development of upscaling technology. 

any recommendation to determine or calculate Encoder and Decoder Tile Size? 

im upscaling some old images, but im getting some seam artficacts, here the settings:

![settingsx2](https://user-images.githubusercontent.com/41844714/223890833-a9fbe3d1-62e8-428a-95ba-5a4ea7de6714.JPG)

**Comment by pkuliyi2015** [comment]
The seam artifact is usually from the multidiffusion rather than tiled VAE, if I'm not doing anything wrong.

To verify this, you can just run with another seed to see if the artifact remains unchanged.

If so, you can fix in to ways:

 -  Increase denoising steps (20->25)
 -  Increase overlap (32->48)

However, both of which will at a cost of running speed. Only try if you encountered seams.

By the way I'm fixing a norm shift that seems to make the edge of resulting photos slightly blur. It will be done soon.
